var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                 xxxxx          ",
   "                                                                 x!!!x          ",
   "                                                                  xvx           ",
   "                                                                                ",
   "                                                                            xx  ",
   "  xx                                                                         x  ",
   "  x          xxxx                                                            x  ",
   "  x         xx!!xx          xx                                               x  ",
   "  x        xx!!!!xx        xxxx                        x                     x  ",
   "  x@      xx!!!!!!xx=     xxxxxx     = x                         xxxxx       x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xx  xxxxx         xxxxxx   xxxxxxxox  ",
   "                                                  x         x              xxx  ",
   "                                                  x!!!!!!!!!x                   ",
   "                                                  x!!!!!!!!!x                   ",
   "                                                  xxxxxxxxxxx                   ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "         xxxxx                xxxxx                xxxxx                xxxxx                xxxxx               ",
   "         x!!!x                x!!!x                x!!!x                x!!!x                x!!!x                ",
   "         x!!!x                x!!!x                x!!!x                x!!!x                x!!!x                ",
   "         xxvxx                xxvxx                xxvxx                xxvxx                xxvxx                ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "  @                                                                                                               ",
   "xxxnxxxxnxxxnxxnxxxxxxnxxxnxxnxxxxxxnxxxxxxxnxxxxxxnxxxxxxnxxxxxnnnxxxxxxnxxxxnxxxxxxnxxnxxnxxxxnxxxxxnxxxnxxx o x",
   "                                                                                                             xnxnx",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  "],
  [" xxxxxxxxx                                                                                                        ",
   " x @     x                                                                                                        ",
   " xxxxx   x                                                                                                        ",
   " x!!!x   x                                                                                                        ",
   " xxvxx   x                                                                                                        ",
   " x       x       x       x       x        x       x        x       x        x       x       x                    x",
   " x       x       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    x",
   " x       x       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x   x                x",
   " x     xxx       xxxxxxxvxxxvxxxvxxxvxxxxxxxxxxxxxxxxxxxxxxxxxvxxxxxxxxxvxxxxxxxxxxxxxxxxxxxx                    x",
   " x    x         xx                                       x                   x                     x    x        x",
   " x   x    o    xx                                        x                   x                                   x",
   " x   xxxxxxxxxxx                                         x         x         x                             x     x",
   " x                 xxxxxxxxxxxxxxxxxxxxx        xxxx     xxx       x       xxx                                   x",
   " x              = xx                       xx      x     x         x         x                               x   x",
   " xxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    x         x         x                                    x",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x     x         x         x                            x      x",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x     x       xxxxx       x                                   x",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x     x         x         x                         x         x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvxxvxxxxxx     x         x         x                                   x",
   "x                                                  x     x         x         x                      x            x",
   "x                                                  x     xxx       x       xxx                                   x",
   "x    xxx                                   xxx           x         x         x                  x                x",
   "x    x!!x                               xxx!!!xxx        x         x         x                                   x",
   "x    x!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!xxxxxxxxx         x         x              x                    x",
   "x    x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       xxxxx       x                                   x",
   "x    xxxxxvxxxxxxxxxxxxxxxxxxxvxxxxxxxxxxxxxxxxxxxxxvxxxxx         x         x         x                         x",
   "x                                                                  x                                             x",
   "x                                                                  x              xxx                            x",
   "xxxxxxxxxxxxxxxx  =                          =  xxxxxxxxxxxxxxxxxxxxx!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "               xxxxxxxxxnxxxxxxxxxxxxxxxxxxxxxxxx                   xxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                  xxx x       ",
   "                                                                                                     cx       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                 ox           ",
   "                                                                                                xxx xxx       ",
   "                                                                                                  x x x       ",
   "                                                                                                  xxx x       ",
   "                   xxx                                                                                x       ",
   "       !     !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x=    x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !     !                                               xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "                         xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xnx                                                                            ",
   "                                                                                                              ",
   "                                                                                x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x   xxxxxxxxx   xxxxxxxxx   xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx       xxxxx       xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xn     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxnxxxxxxxxxxxxxxxxxxxnxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
